### ISSUE TITLE
Things to fix

### ISSUE THREAD

**Issue by kuntzer** [vbonvin/POUET#26]
**what is in bold is to be fixed NOW for v0.3**
The rest will be fixed later

- [x]  Resize window
- [x] **add possibility to select name / export selected**
- [x] fix loading of rdb empty columns
- [x] JPG -> jpg (OSError: file not understood?) Apparently a mac issue, please try to reproduce. However changing .JPG->.jpg might help
- [x] thread to reload all sky
- [x] Updates when changing mode [edit:] already done, nothing to do
- [x] print_status when updating
- [x] add clouds in flag observability
- [x] positions of the tabs --> separators in layouts? [edit:] changed the size of status box
- [x] **Rename smartly the buttons (select --> checked | plot--> display | display selected --> sort | display all --> reset list)**
- [x] **Problem when loading catalogs !!!**

------- 
From olga's post below:

- [x]  **Replacement: add a right click drop-down menu to chose which plot the user want (airmass, sky chart, etc...)  |  Original: When clicking on the object, airmass chart and finding chart appear at the same place on the screen - airmass chart gets hidden by the sky chart. Maybe it would be more logical if the airmass chart appears when you click on the airmass value for the object? Or you create separate buttons. For example, an eye button next to the object name to display the sky chart.**

- [x] On airmass chart put precisely what time are you using (1:00 UT or smth else).

- * Replacement: Force a single display style (UNIX style) | Original :On Mac OS the buttons on the sky chart look weird + NEAT and 2MASS-J survey charts look bizarre as well
<img width="671" alt="screen shot 2018-02-27 at 19 02 00" src="https://user-images.githubusercontent.com/16881048/36763167-8d3c261e-1c05-11e8-8d68-7f47ce85efc4.png">

- [x] Even with the small window size some buttons still look funky. And the window with targets is trifle too small, so need to scroll left-right to see all the params. The egg chart gets poorly readable, especially with targets plotted on it. So dynamic resizing would be nice :)
<img width="1178" alt="screen shot 2018-02-27 at 21 22 30" src="https://user-images.githubusercontent.com/16881048/36763326-34d6062e-1c06-11e8-93a2-2a2122cb4a07.png">

- [x] Also, with the small window size, in the Station tab Moon coordinates get eaten away. Similar for the Configuration tab.
<img width="742" alt="screen shot 2018-02-28 at 00 51 43" src="https://user-images.githubusercontent.com/16881048/36769228-c2d81da2-1c21-11e8-932c-c72d686293e5.png">

- [x] In the Station tab name button Refresh instead of Refresh now.

- * The cloud analysis is completely degenerate with the presence of the moon. Now the moon is out, so you don't see stars cause the moon is too bright, but the sky is completely clear. Your cloud analysis is showing clouds on most parts of the sky.
<img width="460" alt="screen shot 2018-02-27 at 21 38 23" src="https://user-images.githubusercontent.com/16881048/36763445-ba9b06ce-1c06-11e8-98bf-6873d72f5bde.png">
<img width="464" alt="screen shot 2018-02-27 at 21 38 32" src="https://user-images.githubusercontent.com/16881048/36763457-c8d3f034-1c06-11e8-826e-21ccdcf262d7.png">

- [x] Pouet quit unexpectedly quite a few times with the following error:

  File "main.py", line 1925, in run
    allskycopy.update(float(SETTINGS['validity']['allskyfrequency']))
  File "POUET-0.3.0/pouet/clouds.py", line 97, in update
    x, y = self.detect_stars()
  File "POUET-0.3.0/pouet/clouds.py", line 124, in detect_stars
    delta_arr = data_max - data_min
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Abort trap: 6 

* Please put confused Travolta https://www.youtube.com/watch?v=dxyRy_xw-cU when pouet can't load the clouds instead of this ugly black cross! :) Also, once Travolta has appeared/disappeared, if there is still no connection to the all-sky cam, you could load some default picture, for example the one for the day time. So that there would be still a possibility to plot the targets on the sky and draw the wind boundaries. 

- [x] In cat703 when selecting targets with respect to the airmass <= 1.0, it displays 0 targets, although there are plenty with that value for airmass.

- [x] **In cat714 when trying to select with respect to the airmass, quit with the error**

Traceback (most recent call last):
  File "main.py", line 896, in hide_observables
    run.hide_observables(self.observables, criteria)
  File "POUET-0.3.0/pouet/run.py", line 62, in hide_observables
    if  o.airmass > c["max"]:
AttributeError: 'Observable' object has no attribute 'airmass'
Abort trap: 6

- * Try do have a different displayed value and stored value: Original | when you display Moon angle and Wind you have a 0 followed by two digit numbers, like 045. 

- [x] When you load the catalogue, you could analyse the keywords contained in it and propose the most likely matching ones for Name, Ra and Dec instead of just the first ones in the row. Like smth containing alpha or ra for RA. Similarly like the TopCat is doing it.

- [x] **It would be good to display what catalogue is currently loaded.** 

- [x] Once objects are plotted, there is no button to un-plot them. The work-around is to select no targets and plot them, which clears the sky and egg plot, but I think the explicit button would be a more clean solution. Or make it like with (De)select -> (Un)plot selected targets.

- * When you enter the criteria for the object selection, it is very cool that it gets color coded. But if you have messed up and it is red, then it might be complicated to get back to green. So maybe you can put the Reset parameters button.

- [x] Replace: will be fixed when working on the dynamic dispaly. Original: I find that this obj selection and display panel is not very user friendly. There is a easy confusion between Display selected and Plot selected targets. I would rearrange the things a bit like that 
<img width="775" alt="screen shot 2018-02-28 at 01 14 54" src="https://user-images.githubusercontent.com/16881048/36769712-d3808808-1c24-11e8-87d2-53aea45f56b4.png">

- [x] **When you load the new catalogue, the plotted objects from the previous one still hang on the sky - could clear them away while loading new cat.**

- [x] **You display cloud flag 0.0 as red. I think it would be more logical to flag clouds=0.0 as green and absence of the clouds. And make cloud=1 as presence of them. So to invert the scale.**

- [x] It might be useful to show Chilean time next to UT time. 

- [x] **Doc: find a way to have exec() in main.py correctly executed in readthedocs**

- [x] **Doc: complete the documentation**

- [x] **Doc: mini tutorial --> cooquebouque + hauoutou**

- [x] **Doc: nice welcome page**

- [x]  Improve the test coverage

**Comment by kuntzer** [comment]
In compute_observability I changed the 

    self.observability -= ....

to 

    self.observability *= 0.75

to reduce the observability when not perfect conditions but still okay.

**Comment by olgatihhonova** [comment]
* When clicking on the object, airmass chart and finding chart appear at the same place on the screen - airmass chart gets hidden by the sky chart. Maybe it would be more logical if the airmass chart appears when you click on the airmass value for the object? Or you create separate buttons. For example, an eye button next to the object name to display the sky chart.

* On airmass chart put precisely what time are you using (1:00 UT or smth else).

* On Mac OS the buttons on the sky chart look weird + NEAT and 2MASS-J survey charts look bizarre as well
<img width="671" alt="screen shot 2018-02-27 at 19 02 00" src="https://user-images.githubusercontent.com/16881048/36763167-8d3c261e-1c05-11e8-8d68-7f47ce85efc4.png">

* Even with the small window size some buttons still look funky. And the window with targets is trifle too small, so need to scroll left-right to see all the params. The egg chart gets poorly readable, especially with targets plotted on it. So dynamic resizing would be nice :)
<img width="1178" alt="screen shot 2018-02-27 at 21 22 30" src="https://user-images.githubusercontent.com/16881048/36763326-34d6062e-1c06-11e8-93a2-2a2122cb4a07.png">

* Also, with the small window size, in the Station tab Moon coordinates get eaten away. Similar for the Configuration tab.
<img width="742" alt="screen shot 2018-02-28 at 00 51 43" src="https://user-images.githubusercontent.com/16881048/36769228-c2d81da2-1c21-11e8-932c-c72d686293e5.png">

* In the Station tab name button Refresh instead of Refresh now.

* The cloud analysis is completely degenerate with the presence of the moon. Now the moon is out, so you don't see stars cause the moon is too bright, but the sky is completely clear. Your cloud analysis is showing clouds on most parts of the sky.
<img width="460" alt="screen shot 2018-02-27 at 21 38 23" src="https://user-images.githubusercontent.com/16881048/36763445-ba9b06ce-1c06-11e8-98bf-6873d72f5bde.png">
<img width="464" alt="screen shot 2018-02-27 at 21 38 32" src="https://user-images.githubusercontent.com/16881048/36763457-c8d3f034-1c06-11e8-826e-21ccdcf262d7.png">

* Pouet quit unexpectedly quite a few times with the following error:

  File "main.py", line 1925, in run
    allskycopy.update(float(SETTINGS['validity']['allskyfrequency']))
  File "POUET-0.3.0/pouet/clouds.py", line 97, in update
    x, y = self.detect_stars()
  File "POUET-0.3.0/pouet/clouds.py", line 124, in detect_stars
    delta_arr = data_max - data_min
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Abort trap: 6 

* Please put confused Travolta https://www.youtube.com/watch?v=dxyRy_xw-cU when pouet can't load the clouds instead of this ugly black cross! :)

* In cat703 when selecting targets with respect to the airmass <= 1.0, it displays 0 targets, although there are plenty with that value for airmass.

* In cat714 when trying to select with respect to the airmass, quit with the error

Traceback (most recent call last):
  File "main.py", line 896, in hide_observables
    run.hide_observables(self.observables, criteria)
  File "POUET-0.3.0/pouet/run.py", line 62, in hide_observables
    if  o.airmass > c["max"]:
AttributeError: 'Observable' object has no attribute 'airmass'
Abort trap: 6

* When you display Moon angle and Wind you have a 0 followed by two digit numbers, like 045. 

* When you load the catalogue, you could analyse the keywords contained in it and propose the most likely matching ones for Name, Ra and Dec instead of just the first ones in the row. Like smth containing alpha or ra for RA. Similarly like the TopCat is doing it.

* It would be good to display what catalogue is currently loaded. 

* Once objects are plotted, there is no button to un-plot them. The work-around is to select no targets and plot them, which clears the sky and egg plot, but I think the explicit button would be a more clean solution. Or make it like with (De)select -> (Un)plot selected targets.

* When you enter the criteria for the object selection, it is very cool that it gets color coded. But if you have messed up and it is red, then it might be complicated to get back to green. So maybe you can put the Reset parameters button.

* I find that this obj selection and display panel is not very user friendly. There is a easy confusion between Display selected and Plot selected targets. I would rearrange the things a bit like that 
<img width="775" alt="screen shot 2018-02-28 at 01 14 54" src="https://user-images.githubusercontent.com/16881048/36769712-d3808808-1c24-11e8-87d2-53aea45f56b4.png">

* When you load the new catalogue, the plotted objects from the previous one still hang on the sky - could clear them away while loading new cat.

* You display cloud flag 0.0 as red. I think it would be more logical to flag clouds=0.0 as green and absence of the clouds. And make cloud=1 as presence of them. So to invert the scale.

**Comment by kuntzer** [comment]
Thanks @olgatihhonova for the feedback. Note that this won't be "fixed" :D 

> Please put confused Travolta https://www.youtube.com/watch?v=dxyRy_xw-cU when pouet can't load the clouds instead of this ugly black cross! :) Also, once Travolta has appeared/disappeared, if there is still no connection to the all-sky cam, you could load some default picture, for example the one for the day time. So that there would be still a possibility to plot the targets on the sky and draw the wind boundaries.

HOWEVER you can used the "debug mode" to have a value of the wind and the all sky

**Comment by kuntzer** [comment]
This doesn't close the GUI when executing on linux:

> Pouet quit unexpectedly quite a few times with the following error:

    File "main.py", line 1925, in run 
    allskycopy.update(float(SETTINGS['validity']['allskyfrequency']))
    File "POUET-0.3.0/pouet/clouds.py", line 97, in update
    x, y = self.detect_stars()
    File "POUET-0.3.0/pouet/clouds.py", line 124, in detect_stars
    delta_arr = data_max - data_min
    TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
    Abort trap: 6

Added a `try/except` rule to deal with the faulty line. It is due to a partial download of the image (like when the server updates the file you're downloading...

**Comment by kuntzer** [comment]
> When you display Moon angle and Wind you have a 0 followed by two digit numbers, like 045.

won't fix. Needed for correct ordering the numbers (yes it is a stupid order selector, but it's not us, it pyqt...)

**Comment by kuntzer** [comment]
TODO (note to self):

moon stuff in all sky:  cannot fix that well, have to work with the all sky image we have. However: look if high background. If too high, return None instead of a number...

**Comment by olgatihhonova** [comment]
> Thanks @olgatihhonova for the feedback. Note that this won't be "fixed" :D
> 
> Please put confused Travolta https://www.youtube.com/watch?v=dxyRy_xw-cU when pouet can't load the clouds instead of this ugly black cross! :) Also, once Travolta has appeared/disappeared, if there is still no connection to the all-sky cam, you could load some default picture, for example the one for the day time. So that there would be still a possibility to plot the targets on the sky and draw the wind boundaries.
> HOWEVER you can used the "debug mode" to have a value of the wind and the all sky

I still think it would be good to load a different photo in the case the sky-cam is not accessible, not the one of the debug mode. With a warning saying that all-sky cam is not accessible. Cause in the debug mode, there are clouds, so it might be confusing.

**Comment by vbonvin** [comment]
Items marked for v0.3 have been copied in the open post. Items marked for v0.4 have been split in single issues.

**Comment by kuntzer** [comment]
I'm only testing the issue chat to see whether I lost my picture

**Comment by kuntzer** [comment]
Okay, no, plus I still have the collaborator tag!

**Comment by vbonvin** [comment]
Dynamic display is live!

Well, except for the plots because it's a mess to dynamically resize them, and I think we can live with them having a fixed size.

**Comment by kuntzer** [comment]
Very nice job Dr @vbonvin !

**Comment by vbonvin** [comment]
Tentative plan for the documentation 

<script src="https://gist.github.com/vbonvin/cb59a391c1ce272ed79a911776cefaad.js"></script>

**Comment by vbonvin** [comment]
Doc-related points moved to dedicated issues (#40 to #48)
